config/routes.rb
Donation::Application.routes.draw do
  root to: "companies#index"
  devise_for :users
  resources :users
  resources :companies
  resources :contributions
  resources :subscriptions
  resources :plans
  resources :recipients
end

app/controllers/recipients_controller.rb
class RecipientsController < ApplicationController
  def new
    @company = Company.new
    @company = Company.find(params[:id]) if params[:id]
  end

  def create
    recipient = Stripe::Recipient.create(
      :name => params[:name],
      :type => params[:type],
      :email => params[:email],
      :bank_account => {
        :country => params[:country],
        :routing_number => params[:routing],
        :account_number => params[:account]
      }
    )
    transfer = Stripe::Transfer.create(
      :amount => params[:amount].to_i * 100, # amount in cents
      :currency => params[:currency],
      :recipient => recipient,
      :statement_description => params[:description]
    )
    flash[:notice] = "Transfer sent!"
    redirect_to :back
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to :back
  end

# private

#   def recipient_params
#     params.require(:recipient).permit(:email, :type, :name, :bank_account)
#   end
end

app/views/recipients/new.html.erb
<% if @company.name %>
  <h2><%= @company.name %></h2>
  <h4><%= @company.description %></h4>

  <h1>Create a transfer</h1>
    <article>
    <%= form_tag recipients_path do %>
      <div class="form-group">
        <%= text_field_tag :name, nil, placeholder: "Recipient Name" %>
      </div>
      <div class="form-group">
        <%= radio_button_tag(:type, "individual") %>
        <%= label_tag(:type, "Individual") %>
        <%= radio_button_tag(:type, "corporation") %>
        <%= label_tag(:type, "Corporation") %>
      </div>
      <div class="form-group">
        <%= email_field_tag :email, nil, placeholder: "Email" %>
      </div>
      <div class="form-group">
        <%= text_field_tag :account, "000123456789", placeholder: "Bank Account Number" %>
        <%= text_field_tag :routing, "110000000", placeholder: "Bank Routing Number" %>
      </div>
      <div class="form-group">
        <%= text_field_tag :country, nil, placeholder: "Country" %>
      </div>
      <div class="form-group">
        <%= number_field_tag :amount, nil, placeholder: "Amount" %>
        <%= select_tag :currency, options_for_select(currency) %>
      </div>
      <div class="form-group">
        <%= text_field_tag :description, nil, placeholder: "Description" %>
      </div>
      <%= hidden_field_tag :company_id, value: @company.id %>
      <%= submit_tag "Send Money!", class: "btn btn-danger btn-lg" %>
    <% end %>
    </article>
<% else %>
  <h1>YOU SHALL NOT PASS!!!!!</h1>
  <%= link_to "Return to Companies", companies_path, class: "btn btn-primary btn-lg" %>
<% end %>