config/routes.rb
Donation::Application.routes.draw do
  root to: "companies#index"
  devise_for :users
  resources :users
  resources :companies
  resources :contributions
  resources :subscriptions
  resources :plans
  resources :recipients
end

app/models/company.rb
class Company < ActiveRecord::Base
  belongs_to :user
  has_many :plans
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :create]

  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    if params[:company]
      @company.update(company_params)
    end
      redirect_to company_path
  end

  def create
    @company = Company.new(company_params)
    if @company.save
      flash[:notice] = "Company created!"
      redirect_to :back
    else
      redirect_to :back
    end
  end

  def destroy
    @company = Company.find(params[:id])
    @company.destroy
    redirect_to root_path
  end

private

  def company_params
    params.require(:company).permit(:name, :description, :user_id)
  end
end

app/views/companies/_form.html.erb
<%= form_for @company do |f| %>
  <div class="form-group margin-high">
    <%= f.text_field :name, placeholder: "Name" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, cols: 35, rows: 7,placeholder: "Description" %>
  </div>
  <%= f.hidden_field :user_id, value: current_user.id if current_user %>
  <%= f.submit class: "btn btn-success" %>
<% end %>

app/views/companies/edit.html.erb
<%= render 'form' %>

app/views/companies/index.html.erb
<h1>Companies</h1>

<ul>
<% @companies.each do |company| %>
  <p><%= link_to company.name, company_path(company) %></p>
<% end %>

app/views/companies/new.html.erb
<%= render 'form' %>

app/views/companies/show.html.erb
<h1><%= @company.name %></h1>

<p> <%= @company.description %> </p>

  <% if current_user && current_user.id == @company.user_id %>
    <%= link_to "Create Recurring Plans", new_plan_path(id: @company.id), :class=> "btn btn-info" %>
    <%= link_to "Transfer Money", new_recipient_path(id: @company.id), :class=> "btn btn-success" %>
    <%= link_to "Edit Company", edit_company_path, :class=> "btn btn-warning" %>
    <%= link_to "Delete", company_path(@company),
                        :confirm => "You sure?",
                        :method => "delete",
                        :class => "btn btn-danger" %>
  <% else %>
    <%= link_to "One Time Donation!", new_contribution_path(id: @company.id), :class=> "btn btn-success" %>
    <%= link_to "Recurring Donation!", new_subscription_path(id: @company.id), :class=> "btn btn-primary" %>
  <% end %>