config/routes.rb
Donation::Application.routes.draw do
  root to: "companies#index"
  devise_for :users
  resources :users
  resources :companies
  resources :contributions
  resources :subscriptions
  resources :plans
  resources :recipients
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  def new
    @company = Company.new
    @company = Company.find(params[:id]) if params[:id]
  end

  def create
    @company = Company.find(params[:company_id])
    @plan = params[:plan]

    customer = Stripe::Customer.create(
      :card => params[:stripeToken],
      :plan => @plan,
      :email => params[:stripeEmail]
    )
    flash[:notice] = "You're going to have a #{@plan}!"
    redirect_to :back
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to companies_path
  end
end

app/views/subscriptions/new.html.erb
<% if @company.name %>
  <h2><%= @company.name %></h2>
  <h4><%= @company.description %></h4>

  <%= form_tag subscriptions_path do %>
    <article>
      <div class="form-group">
        <%= radio_button_tag(:plan, "crabby-month") %>
        <%= label_tag(:plan, "Crab Friends - $35,000 per month") %>
      </div>
      <div class="form-group">
        <%= radio_button_tag(:plan, "crabby-year") %>
        <%= label_tag(:plan, "SUPER Crab Friends - $777,777.77 per year") %>
      </div>
      <%= hidden_field_tag :company_id, @company.id %>
    </article>

    <br>
    <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
            data-description="Pay me my money!!!!"></script>
  <% end %>
<% else %>
  <h1>YOU SHALL NOT PASS!!!!!</h1>
  <%= link_to "Return to Companies", companies_path, class: "btn btn-primary btn-lg" %>
<% end %>