config/routes.rb
Donation::Application.routes.draw do
  root to: "companies#index"
  devise_for :users
  resources :users
  resources :companies
  resources :contributions
  resources :subscriptions
  resources :plans
  resources :recipients
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>
    <%= content_for?(:title) ? yield(:title)+" | Non-Profit Donation" : "Non-Profit Donation" %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => false %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div class="container" id="main">
    <div class="navbar navbar-default navbar-fixed-top">
    <%= link_to "Home", root_url, class: "navbar-brand pull-left" %>
    <% if user_signed_in? %>
      <%= link_to "Create Company", new_company_path, class: "navbar-text pull-left" %>
      <%= link_to "Log Out", destroy_user_session_path, method: "delete", class: "navbar-text pull-right" %>
      <div class="navbar-text pull-right">
        Logged in as &nbsp; <%= link_to current_user.email, user_path(current_user) %>
      </div>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, class: "navbar-text pull-right" %>
      <%= link_to "Log In", new_user_session_path, class: "navbar-text pull-right" %>
    <% end %>
  </div>
     <%- flash.each do |name, msg| -%>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      <%- end -%>
<img src="http://lorempixel.com/400/200">
<%= yield %>

</div>
</body>
</html>